# Slackware versions: 3.3, 8.1, 9.0, ..., 15.0, ..., current
OS_VERSION=15.0

# Latest stable Slackware release
# (the SBo repository does not have a "current" branch)
OS_LAST_RELEASE=15.0

# Repository metadata location (PACKAGES.TXT, SLACKBUILDS.TXT):
# default: /var/lib/spman/
REPOS_PATH=/var/lib/spman/

# Repository logs location (ChangeLog.txt):
# default: /var/log/spman/
LOGS_PATH=/var/log/spman/

# Package queue directory:
# default: /root/spman/queue/
QUEUE_PATH=/root/spman/queue/

# Directory for downloading source code, build scripts, and binary packages:
# default: /root/spman/build/
BUILD_PATH=/root/spman/build/

# Output directory for built packages:
# default: /root/spman/build/
OUTPUT_PATH=/root/spman/build/

# Package file extension (txz or tgz):
# default: txz
PKGTYPE=txz
