#!/usr/bin/env python3
#
#    _________  ____ ___  ____ _____
#   / ___/ __ \/ __ `__ \/ __ `/ __ \
#  (__  ) /_/ / / / / / / /_/ / / / /
# /____/ .___/_/ /_/ /_/\__,_/_/ /_/
#     /_/
#
# spman - Slackware package manager
# Home page: https://github.com/MyRequiem/spman
#
# Copyright (c) 2018 Vladimir MyRequiem Astrakhan, Russia
# <mrvladislavovich@gmail.com>
# All rights reserved
# See LICENSE for details.

"""spman - Slackware package manager."""

import sys

from spman.checkuser import check_root_user
from spman.main import Main


def start() -> int:
    """Application entry point.

    Validates root privileges, verifies system dependencies, and triggers the
    main application loop.
    """
    try:
        check_root_user()

        exit_code = Main().start()
    except PermissionError as err:
        print(f"Error: {err}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\nInterrupted by user.", file=sys.stderr)
        return 130

    return exit_code if exit_code is not None else 0

if __name__ == "__main__":
    sys.exit(start())
