#! /usr/bin/env python3
# -*- coding: utf-8 -*-

# spman file is part of spman
#
# spman - Slackware package manager
# Home page: https://github.com/MyRequiem/spman
#
# Copyright (c) 2018 Vladimir MyRequiem Astrakhan, Russia
# <mrvladislavovich@gmail.com>
# All rights reserved
# See LICENSE for details.


"""
spman - Slackware package manager
"""

import sys

from spman.checkmaindeps import check_main_deps
from spman.checkuser import check_root_user
from spman.main import Main


def start():
    """
    point entry
    """
    # spman can only be run as root
    check_root_user()
    # check dependencies for program
    check_main_deps()
    Main().start()


if __name__ == '__main__':
    sys.exit(start())
